### ISSUE TITLE
How to handle IDirect3DDevice9::Reset(...)? (for switching between Fullscreen and Windowed)

### ISSUE THREAD

**Issue by tobii-dev** [unknowntrojan/egui-d3d9#12]
When switching between full-screen and windowed mode inside my d3d9 app (pressing <kbd>Alt</kbd><kbd>⏎</kbd>), it crashes if I'm drawing egui stuff. This makes sense, as per the docs: https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-reset

> Calling IDirect3DDevice9::Reset causes all texture memory surfaces to be lost, managed textures to be flushed from video memory, and all state information to be lost. Before calling the IDirect3DDevice9::Reset method for a device, an application should release any explicit render targets, depth stencil surfaces, additional swap chains, state blocks, and D3DPOOL_DEFAULT resources associated with the device.

> Pixel shaders and vertex shaders survive IDirect3DDevice9::Reset calls for Direct3D 9. They do not need to be re-created explicitly by the application.

It would be nice if there was a way to handle this on the egui side. I tried looking for examples on how other egui-*backend* crates handle this, but I didn't find anything simple. I found this: https://github.com/derivator/egui_vulkano/blob/41362f02897ca63fa6f26fb3a9b093b9973d839a/examples/example.rs#L278 on the egui_vulkano back-end, and this https://github.com/MatchaChoco010/egui-winit-ash-integration/blob/540a0bb2375991139312d79d691c308b166bf110/examples/example/main.rs#L1827 on egui-winit-ash-integration, but they're not really the same.

Here is an example on how the directx9 imgui back-end handles this:
https://github.com/ocornut/imgui/blob/956a1a17fb8f8d72726cad92f203cdd57470eae7/examples/example_win32_directx9/main.cpp#L165

They invalidate the textures, call device.Reset(...), and create it again.

It would be useful if this crate had something similar, like

```rust
impl<T> EguiDx9<T> {
    /// Call me before my IDirect3DDevice9 gets Reset(...)!
    pub fn invalidate(&mut self, dev: &IDirect3DDevice9, ppresentationparameters: &D3DPRESENT_PARAMETERS) {
        self.drop_stuff_that_will_be_flushed_by_the_reset();
        self.try_to_use_new_window(&ppresentationparameters);
    }
}
```

Is this possible, or should I handle the full-screen switching a different way?

**Comment by unknowntrojan** [comment]
Added a mechanism to survive a reset in 33e50b5. Also bumped the crate version to 0.3. Take a look at the example and how the reset is implemented. Let me know how it goes.

**Comment by unknowntrojan** [comment]
did it work out?

**Comment by tobii-dev** [comment]
> Added a mechanism to survive a reset in [33e50b5](https://github.com/unknowntrojan/egui-d3d9/commit/33e50b51812f3c4596c3f1a9557936032e7da919). Also bumped the crate version to 0.3. Take a look at the example and how the reset is implemented. Let me know how it goes.

I upgraded to 0.3.0 and added the following to my Reset() hook, like in the example:
```rust
unsafe extern "system" fn HOOK_Reset(
	this: IDirect3DDevice9,
	ppresentationparameters: *mut D3DPRESENT_PARAMETERS,
) -> HRESULT {
	trace!("HOOK_Reset_A!");
	let fn_Reset = FN_ORG_RESET.unwrap();
	let r = fn_Reset(this.clone(), ppresentationparameters);
	trace!("HOOK_Reset_B!");
	crate::gui::console::reset(&this);
	trace!("HOOK_Reset_C!");
	r
}
```

the ``crate::gui::console::reset(...)`` function looks like this:
```rust
/// Used reallocate the APP textures that got destroyed during a IDirect3DDevice9::Reset(...)
pub fn reset(dev: &IDirect3DDevice9 /*, _hwnd: HWND*/) {
	if let Some(app) = unsafe { APP.as_mut() } {
		log::trace!("Calling app.reset(dev)...");
		app.reset(dev);
		log::trace!("app.reset(dev) returned!!");
	}
}
```

Full code here:
https://github.com/tobii-dev/blur-hooks-rs/blob/3504b990930c6a173978da223410c73863182ca6/src/dll/f_direct3d9.rs#L108


I'm crashing with the following stack-trace:
```
14:16:17 [INFO] MyD3D9::GetAdapterIdentifier
14:16:43 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:112] HOOK_Reset_A!
14:16:43 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:115] HOOK_Reset_B!
14:16:43 [TRACE] (2) d3d9::gui::console: [src\gui\console.rs:45] Calling app.reset(dev)...
14:16:43 [ERROR] thread '<unnamed>' panicked at 'Failed to create vertex buffer: Error { code: HRESULT(0x8876086C), message: "" }': C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\egui-d3d9-0.3.0\src\mesh.rs:110
   0: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\backtrace\mod.rs:53
   1: backtrace::capture::Backtrace::create
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\capture.rs:176
   2: backtrace::capture::Backtrace::new
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\capture.rs:140
   3: backtrace::capture::impl$8::default
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.67\src\capture.rs:410
   4: alloc::vec::Vec::append_elements
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\alloc\src\vec\mod.rs:1942
   5: alloc::vec::spec_extend::impl$4::spec_extend
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\alloc\src\vec\spec_extend.rs:55
   6: alloc::vec::Vec::extend_from_slice
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\alloc\src\vec\mod.rs:2386
   7: alloc::string::String::push_str
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\alloc\src\string.rs:926
   8: alloc::string::impl$67::write_str
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\alloc\src\string.rs:2880
   9: core::fmt::impl$0::write_str<alloc::string::String>
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\mod.rs:199
  10: core::fmt::write
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\mod.rs:1118
  11: core::fmt::Formatter::write_fmt
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\mod.rs:1560
  12: windows::core::strings::hstring::impl$9::fmt
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.48.0\src\core\strings\hstring.rs:149
  13: windows::core::strings::hstring::HSTRING::is_empty
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.48.0\src\core\strings\hstring.rs:19
  14: core::fmt::builders::impl$3::finish::closure$0
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\builders.rs:226
  15: core::result::Result::and_then
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\result.rs:1319
  16: core::fmt::builders::DebugStruct::finish
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\builders.rs:225
  17: core::ptr::drop_in_place<windows::core::strings::hstring::HSTRING>
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220\library\core\src\ptr\mod.rs:497
  18: core::fmt::impl$53::fmt<dyn$<core::fmt::Debug> >
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\mod.rs:2268
  19: core::fmt::rt::Argument::fmt
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\rt.rs:138
  20: core::fmt::write
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\mod.rs:1094
  21: core::fmt::Write::write_fmt
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\fmt\mod.rs:192
  22: std::panicking::begin_panic_handler::impl$0::fill::closure$0
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\std\src\panicking.rs:559
  23: core::option::Option::get_or_insert_with
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\option.rs:1665
  24: std::panicking::begin_panic_handler::PanicPayload::fill
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\std\src\panicking.rs:557
  25: std::panicking::begin_panic_handler::impl$1::get
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\std\src\panicking.rs:575
  26: <unknown>
  27: windows::core::hresult::HRESULT::from_abi<windows::imp::bindings::IErrorInfo>
             at C:\Users\tobii\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.48.0\src\core\hresult.rs:78
  28: _xmm
  29: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\std\src\sys_common\backtrace.rs:151
  30: std::panicking::begin_panic_handler
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\std\src\panicking.rs:593
  31: core::panicking::panic_fmt
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\panicking.rs:67
  32: core::result::unwrap_failed
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library\core\src\result.rs:1651
  33: enum2$<core::result::Result<tuple$<>,windows::core::error::Error> >::expect<tuple$<>,windows::core::error::Error>
             at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220\library\core\src\result.rs:1033
  34: DllCanUnloadNow
  35: <unknown>
  36: <unknown>
  37: GetMediaBin
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: OpenVulkanCompiler
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: GTPin_Init
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
```

So I think it's crashing inside the ``.reset(...)`` function, not 100% sure:

https://github.com/unknowntrojan/egui-d3d9/blob/33e50b51812f3c4596c3f1a9557936032e7da919/egui-d3d9/src/app.rs#L67

->

https://github.com/unknowntrojan/egui-d3d9/blob/643091df194b90f082b3214b67074032d3b84d19/egui-d3d9/src/app.rs#L69

->

https://github.com/unknowntrojan/egui-d3d9/blob/643091df194b90f082b3214b67074032d3b84d19/egui-d3d9/src/mesh.rs#L111

**Comment by tobii-dev** [comment]
> did it work out?

I had a look at the MSDN docs and found this:
https://learn.microsoft.com/en-us/windows/win32/direct3d9/lost-devices


I don't understand where or how it is finding vertex buffers that have been released, I thought ``IDirect3DDevice::Reset(...)`` takes care of that. Maybe we have to manually release them before ``IDirect3DDevice::Reset(...)`` gets called? The docs would agree with this:
> Before calling the IDirect3DDevice9::Reset method for a device, an application should release any explicit render targets, depth stencil surfaces, additional swap chains, state blocks, and D3DPOOL_DEFAULT resources associated with the device.

I see imgui-dx3d9 does do the releasing manually: They call 'ImGui_ImplDX9_InvalidateDeviceObjects()' before a ``IDirect3DDevice::Reset(...)``:

https://github.com/ocornut/imgui/blob/956a1a17fb8f8d72726cad92f203cdd57470eae7/examples/example_win32_directx9/main.cpp#L207


Refactored code so its a bit easier to read and understand how they do it:
```cpp
/// https://github.com/ocornut/imgui/blob/956a1a17fb8f8d72726cad92f203cdd57470eae7/backends/imgui_impl_dx9.cpp#L368
void ImGui_ImplDX9_InvalidateDeviceObjects() {
    ImGui_ImplDX9_Data* bd = ImGui_ImplDX9_GetBackendData();
    if (!bd || !bd->pd3dDevice) return;
    if (bd->pVB) {
        bd->pVB->Release(); /// <- This is LPDIRECT3DVERTEXBUFFER9.Release()
        bd->pVB = nullptr;
    } 
    if (bd->pIB) {
        bd->pIB->Release(); /// LPDIRECT3DINDEXBUFFER9.Release()
        bd->pIB = nullptr;
    } 
    if (bd->FontTexture) {
        bd->FontTexture->Release();
        bd->FontTexture = nullptr;
        ImGui::GetIO().Fonts->SetTexID(0); // We copied bd->pFontTextureView to io.Fonts->TexID so let's clear that as well.
    }
}
```


I don't know if this crate should also be doing the releasing manually, as the ~~ C++ Microsoft COM witchcraft in Rust ~~ is pretty confusing to me... I was under the impression that when the Buffers struct has no more references to it, its members would be dropped, so they would be ``.Release()``d (vtx and idx).

Maybe trying something like this would work?
```rust
impl Buffers {
    ...
    pub fn release(&mut self, device: &IDirect3DDevice9) {
        self.vtx.Release();
        self.idx.Release();
        // Handle counts and other stuff I probably forgot :D
    }

}
```

**Comment by unknowntrojan** [comment]
I fixed it. I think. One second.

**Comment by unknowntrojan** [comment]
Please try again with a06d1cd.

**Comment by tobii-dev** [comment]
> Please try again with [a06d1cd](https://github.com/unknowntrojan/egui-d3d9/commit/a06d1cd70860bec77f2cfa7b741cd37eda7b4a49).


crates.io didn't have the 0.3.1 version yet!
```
15:32:31 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:112] HOOK_Reset_A!
15:32:31 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:115] HOOK_Reset_B!
15:32:31 [TRACE] (2) d3d9::gui::console: [src\gui\console.rs:45] Calling app.reset(dev)...
15:32:31 [TRACE] (2) d3d9::gui::console: [src\gui\console.rs:48] app.reset(dev) returned!!
15:32:31 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:117] HOOK_Reset_C!
```
It still crashed, and now I don't get a stacktrace. The fact that it made it to the "HOOK_Reset_C!" trace point thingy means it doesn't crash inside app.reset()! I'll have to do some debugging to find out why it is crashing now.

**Comment by unknowntrojan** [comment]
I didn't push it yet because I'm not sure if it'll work. I don't want some random dudes build breaking.

Also, it's crashing in present. I deferred the re-allocation stuff to present because the device should be ready by then.

I just can't reproduce it, when I call reset, everything works just fine

**Comment by tobii-dev** [comment]
> I didn't push it yet because I'm not sure if it'll work. I don't want some random dudes build breaking.
> 
> Also, it's crashing in present. I deferred the re-allocation stuff to present because the device should be ready by then.

Ah OK!

I just changed resolution manually (through the game menu) and there it didn't crash... It went from fullscreen to windowed, and then back on its own... When switching from windowed to fullscreen, it crashes, no stacktrace. I'll try to figure that out.

**Comment by unknowntrojan** [comment]
Wait, I think I may have found it. Give me a sec

**Comment by unknowntrojan** [comment]
no guarantees, 6deaf58.

I don't know if this fixes it, but it was faulty behavior either way. I was freeing resources *after* calling Reset.

**Comment by tobii-dev** [comment]
```
15:59:36 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:112] HOOK_Reset_A!
15:59:36 [TRACE] (2) d3d9::gui::console: [src\gui\console.rs:45] Calling app.pre_reset()...
15:59:36 [TRACE] (2) d3d9::gui::console: [src\gui\console.rs:47] app.pre_reset() returned!!
15:59:36 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:114] HOOK_Reset_B!
15:59:36 [TRACE] (2) d3d9::dll::f_direct3d9: [src\dll\f_direct3d9.rs:117] HOOK_Reset_C!
```
[EDIT] IT WORKS!
Apologies, I forgot to add "rev = 6deaf588b3d5a72af34208c1db1e9d633e989b89" into the Cargo.toml, I think

**Comment by tobii-dev** [comment]
Thanks for the super quick fix

**Comment by unknowntrojan** [comment]
Glad we could work this out. Have a nice evening!
